In [1]:
#Indexing:
import numpy as np


In [2]:
arr=np.arange(0,11)              

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[4]                                     # Indexing

4

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[-1]

10

In [7]:
arr[3:5]                                     # slicing 

array([3, 4])

In [8]:
arr[2:5]=200                                   # Broadcasting
arr

array([  0,   1, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [9]:
arr

array([  0,   1, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [10]:
s=arr[1:5].copy()                                 # .Copy*() fun

In [11]:
s[:] =22

In [12]:
s

array([22, 22, 22, 22])

In [13]:
arr

array([  0,   1, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [14]:
arr[1:6]=66                                       # Memory pblm occur 

In [15]:
arr

array([ 0, 66, 66, 66, 66, 66,  6,  7,  8,  9, 10])

In [16]:
s.copy()

array([22, 22, 22, 22])

In [17]:
arr.copy()

array([ 0, 66, 66, 66, 66, 66,  6,  7,  8,  9, 10])

In [30]:
arr1=np.arange(1,11)

In [19]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr1[2:7].copy()

array([55, 55, 55, 55, 55])

In [29]:
arr1

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [25]:
arr1

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [31]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# indexing 2d Arr matrix:
mat=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
]  

In [36]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
arr=np.array(mat)

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.shape                               # shape of arr

(3, 3)

In [44]:
arr[1]                                 # indexing of arr

array([4, 5, 6])

In [45]:
arr[2]

array([7, 8, 9])

In [46]:
arr[0][1]                  # 0th row and 1st coln 

2

In [47]:
arr[1][0]

4

In [48]:
arr[2][1]

8

In [ ]:
# 2d arr slicing :

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr[1:,1:]                                  # 2D slicing 

array([[5, 6],
       [8, 9]])

In [58]:
arr[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [62]:
arr[:1,:2]

array([[1, 2]])

In [64]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [66]:
# selection:
a=np.arange(1,11)

In [67]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
a[a>8]

array([ 9, 10])

In [75]:
a * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [76]:
b=a * 2

In [82]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Arithmetic Operations on numpy:


In [78]:
array=np.arange(1,11)


In [79]:
array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
array + 10


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [85]:
array ** 3


array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [86]:
array / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [87]:
array // 10


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int32)

In [ ]:
# Universal Array Functions


In [88]:
np.sqrt(array)                  #Taking Square Roots


array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [89]:
np.exp(array)                  #Calcualting exponential (e^)             


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(array)

10

In [91]:
np.sin(array)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [92]:
np.log(array)


array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])