In [ ]:
# Numpy Exercise:

In [4]:
import numpy as np

In [5]:
#Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
#Create an array of 10 fives
np.ones(10)* 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#Create an array of the integers from 10 to 50
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
#Create an array of all the even integers from 10 to 50
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [34]:
#Create a 3x3 matrix with values ranging from 0 to 8
mat=[
    [0,1,2],
    [3,4,5],
    [6,7,8],
]


In [11]:
np.array(mat)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.16994391])

In [14]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([ 0.22477437, -0.2035962 ,  3.0789436 , -0.98447727,  0.98315139,
       -0.22624817, -0.28928272, -0.03862742, -1.12309636,  0.60007533,
        0.47066691,  0.58029995,  0.58853477,  1.38713749,  1.12494932,
        1.16113091, -1.1533933 ,  1.45254747,  1.33367405, -0.7465706 ,
        1.27004597, -0.18165645, -1.57949563, -0.33028602, -1.12793853])

In [15]:
#Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [16]:
#Numpy Indexing and Selection

In [23]:
mat1=np.arange(1,26)

In [24]:
mat1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [25]:
mat1.shape

(25,)

In [29]:
arr2=mat1.reshape(5,5)

In [27]:
mat1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [30]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
arr2[2:,1:]                            # indexing and section

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [35]:
arr2[3][4]

20

In [57]:
arr2[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [58]:
arr2[4]

array([21, 22, 23, 24, 25])

In [61]:
arr2[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# opterations:

In [67]:
#Get the sum of all the values in mat


325

In [68]:
np.sum(arr2)

325

In [69]:
#Get the sum of all the columns in mat
np.std(arr2)

7.211102550927978

In [73]:
#Get the sum of all the columns in mat
arr2.sum(axis=0)

array([55, 60, 65, 70, 75])

In [74]:
arr2.sum(axis=1)         # sum of rows

array([ 15,  40,  65,  90, 115])