In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np                

In [7]:
lst=[1,2,3,4,5]

In [10]:
np.array(lst)                          #list convrting on array 

array([1, 2, 3, 4, 5])

In [11]:
matrix=[
        [1,2,3],
        [4,5,6],
        [7,8,9],
]

In [12]:
np.array(matrix)                       

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# inbuild fuctions in numpy:
np.arange(0,11,2)                                         #range fuc

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))                                          # zeros fuc

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((3,4))                                                #ones fuc

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,9)                                          # linspace fuc

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [18]:
np.eye(4,4)                                                # eye fn

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [23]:
np.ones(1)

array([1.])

In [25]:
#random
np.random.rand(3)                  #rand fun

array([0.95691957, 0.51313468, 0.65674654])

In [26]:
np.random.rand(4,4)

array([[0.43466211, 0.86720233, 0.48440873, 0.21715826],
       [0.66938963, 0.56188463, 0.16907643, 0.9320801 ],
       [0.69303756, 0.33928479, 0.25257889, 0.19418466],
       [0.65510875, 0.54678606, 0.40270323, 0.91320421]])

In [27]:
np.random.randn(4)                                 # randn fun

array([ 0.01466828,  0.84360603,  2.08327907, -1.19905931])

In [28]:
np.random.randn(3,3)

array([[ 0.75621578, -0.27895696,  2.20132769],
       [-0.7433387 , -0.17138766,  0.85885992],
       [-0.30455732,  0.27224916,  1.05105836]])

In [34]:
np.random.randint(1,6)                              # randint fun

4

In [35]:
np.random.randint(1,6,4)

array([3, 4, 2, 5])

In [38]:
#Array Attributes and Methods
a=np.arange(0,25)

In [39]:
a.shape                                                  #shape and reshape fun

(25,)

In [41]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
a.shape

(25,)

In [43]:
a.max()                                               #max,min,arumax,

24

In [44]:
a.min()

0

In [45]:
a.argmax()

24

In [47]:
a.dtype

dtype('int32')