In [ ]:
pip install pandas

In [ ]:

import numpy as np
import pandas as pd

In [108]:
# create series :
mat=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

In [108]:
# create series :
mat=[
    [1,2,3],
    [4,5,6],
    [7,8,9],
]

In [109]:
ar=np.array(mat)
ar[1]

array([4, 5, 6])

In [39]:
lst=['R','E','N']

In [40]:
pd.Series(data=lst)                             # convert list to series 

0    R
1    E
2    N
dtype: object

In [10]:
lst1=['a','b','c']                                # change default index to lst 1

In [41]:
pd.Series(data=lst,index=lst1)

a    R
b    E
c    N
dtype: object

In [42]:
dic={'Name':'Re','Age':'thity'}

In [43]:
pd.Series(data=dic)                             # dictionary

Name       Re
Age     thity
dtype: object

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
pd.Series(ar[2])                            # Numpy array

0    7
1    8
2    9
dtype: int32

In [16]:
# using an index:


In [57]:
list=[1,2,3,4]

In [18]:
series1=pd.Series(data=list,index=['India','Japan','Korea','US'])

In [19]:
series1

India    1
Japan    2
Korea    3
US       4
dtype: int64

In [47]:
series2=pd.Series(list,index=['India','Japan','Korea','UK'])

In [48]:
series2

India    1
Japan    2
Korea    3
UK       4
dtype: int64

In [49]:
series1 + series2                        #(Add )

India    2.0
Japan    4.0
Korea    6.0
UK       NaN
US       NaN
dtype: float64

In [50]:
actors=["Vijay","Dhanush","Vijaysethupathi","Simbu"]

In [51]:
intdex=[1,2,3,4]

In [52]:
s1=pd.Series(data=actors,index=intdex)

In [53]:
s1

1              Vijay
2            Dhanush
3    Vijaysethupathi
4              Simbu
dtype: object

In [27]:
actors1=['Vijay','Dhanush','Vikram','Simbu']

In [28]:
s2=pd.Series(data=actors1,index=intdex)

In [54]:
s2

1      Vijay
2    Dhanush
3     Vikram
4      Simbu
dtype: object

In [30]:
s1 + s2                                           # join 

1               VijayVijay
2           DhanushDhanush
3    VijaysethupathiVikram
4               SimbuSimbu
dtype: object

In [31]:
#create a dataframes:

In [55]:
data1=np.random.randn(4,4)

In [56]:
data1

array([[ 0.9306131 , -0.19082869,  0.21015518,  0.08711402],
       [-0.21741352,  1.59336776, -0.16642747,  0.6209489 ],
       [-0.63820148,  0.01525413,  0.36790817,  0.19903006],
       [ 0.86997085, -1.46580557, -0.79676236, -0.51992911]])

In [60]:
df=pd.DataFrame(data=data1,columns=lst,index=[1,2,3,4])                # crate a dataframe

In [61]:
lst=['A','B','C','D']

In [62]:
df

A         B         C         D
1  0.930613 -0.190829  0.210155  0.087114
2 -0.217414  1.593368 -0.166427  0.620949
3 -0.638201  0.015254  0.367908  0.199030
4  0.869971 -1.465806 -0.796762 -0.519929

In [63]:
df['B']                                             # using indexing

1   -0.190829
2    1.593368
3    0.015254
4   -1.465806
Name: B, dtype: float64

In [64]:
type(df['B'])

pandas.core.series.Series

In [65]:
df[['A','B']]                                      # get two coln an indexing

A         B
1  0.930613 -0.190829
2 -0.217414  1.593368
3 -0.638201  0.015254
4  0.869971 -1.465806

In [66]:
type(df[['A','B']] )

pandas.core.frame.DataFrame

In [ ]:
# ADD a new columns:

In [67]:
df['E']=df['C'] + df['D']

In [110]:
df                                                         # create a new Colunmns 

A         B         C         D         E states
1  0.930613 -0.190829  0.210155  0.087114  0.297269     RR
2 -0.217414  1.593368 -0.166427  0.620949  0.454521     EE
3 -0.638201  0.015254  0.367908  0.199030  0.566938     NN
4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691     UU

In [69]:
df.drop('E',axis=1)                                             # delete tha new one (temp delete)

A         B         C         D
1  0.930613 -0.190829  0.210155  0.087114
2 -0.217414  1.593368 -0.166427  0.620949
3 -0.638201  0.015254  0.367908  0.199030
4  0.869971 -1.465806 -0.796762 -0.519929

In [ ]:
# if u want delete permently use  inplace=ture 

In [70]:
df.loc[3]                                            # selecting Rows 

A   -0.638201
B    0.015254
C    0.367908
D    0.199030
E    0.566938
Name: 3, dtype: float64

In [71]:
df.loc[1,'B']                                     # selecting Rows and colns 

-0.1908286922075596

In [72]:
df.loc[1,['A','B']]

A    0.930613
B   -0.190829
Name: 1, dtype: float64

In [73]:
df.loc[[1,2],['A','B']]

A         B
1  0.930613 -0.190829
2 -0.217414  1.593368

In [ ]:
# condition selection:

In [74]:
df

A         B         C         D         E
1  0.930613 -0.190829  0.210155  0.087114  0.297269
2 -0.217414  1.593368 -0.166427  0.620949  0.454521
3 -0.638201  0.015254  0.367908  0.199030  0.566938
4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691

In [75]:
df>0                                    # normal df potta bollean la return panum 

A      B      C      D      E
1   True  False   True   True   True
2  False   True  False   True   True
3  False   True   True   True   True
4   True  False  False  False  False

In [77]:
df[df>0]                                              # agumented opretion

A         B         C         D         E
1  0.930613       NaN  0.210155  0.087114  0.297269
2       NaN  1.593368       NaN  0.620949  0.454521
3       NaN  0.015254  0.367908  0.199030  0.566938
4  0.869971       NaN       NaN       NaN       NaN

In [79]:
df[df['A']>0]['B']

1   -0.190829
4   -1.465806
Name: B, dtype: float64

In [81]:
df[df['B']>0][['C','D']]

C         D
2 -0.166427  0.620949
3  0.367908  0.199030

In [85]:
df[(df['A']>0) & (df['B']<1)]                #using and ,Or condition (&,|)

A         B         C         D         E
1  0.930613 -0.190829  0.210155  0.087114  0.297269
4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691

In [ ]:
# more index details:

In [86]:
df

A         B         C         D         E
1  0.930613 -0.190829  0.210155  0.087114  0.297269
2 -0.217414  1.593368 -0.166427  0.620949  0.454521
3 -0.638201  0.015254  0.367908  0.199030  0.566938
4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691

In [87]:
df.reset_index()                       # reset index

index         A         B         C         D         E
0      1  0.930613 -0.190829  0.210155  0.087114  0.297269
1      2 -0.217414  1.593368 -0.166427  0.620949  0.454521
2      3 -0.638201  0.015254  0.367908  0.199030  0.566938
3      4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691

In [88]:
df

A         B         C         D         E
1  0.930613 -0.190829  0.210155  0.087114  0.297269
2 -0.217414  1.593368 -0.166427  0.620949  0.454521
3 -0.638201  0.015254  0.367908  0.199030  0.566938
4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691

In [93]:
newind='RR EE NN UU'.split()                  # .spilt fn automatic ka list la generate aagum

In [94]:
newind

['RR', 'EE', 'NN', 'UU']

In [95]:
df['states']=newind

In [96]:
df

A         B         C         D         E states
1  0.930613 -0.190829  0.210155  0.087114  0.297269     RR
2 -0.217414  1.593368 -0.166427  0.620949  0.454521     EE
3 -0.638201  0.015254  0.367908  0.199030  0.566938     NN
4  0.869971 -1.465806 -0.796762 -0.519929 -1.316691     UU

In [98]:
df.set_index('states')

A         B         C         D         E
states                                                  
RR      0.930613 -0.190829  0.210155  0.087114  0.297269
EE     -0.217414  1.593368 -0.166427  0.620949  0.454521
NN     -0.638201  0.015254  0.367908  0.199030  0.566938
UU      0.869971 -1.465806 -0.796762 -0.519929 -1.316691

In [ ]:
#Multi-Index and Index Hierarchy:

In [120]:
# create muti-index:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
hier_index= zip(outside,inside)
hier_index=pd.MultiIndex.from_tuples(hier_index)


In [121]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [116]:
data2=np.random.randn(6,2)

In [117]:
data2

array([[ 1.06903141,  2.19884189],
       [ 0.3996858 ,  0.4768297 ],
       [ 0.2490381 , -0.30646514],
       [ 0.9060877 ,  0.12858534],
       [-0.65849839, -0.14451891],
       [-0.01532827,  0.2097115 ]])

In [118]:
df1=pd.DataFrame(data=data2,index=hier_index,columns=['A','B'])

In [122]:
df1

A         B
G1 1  1.069031  2.198842
   2  0.399686  0.476830
   3  0.249038 -0.306465
G2 1  0.906088  0.128585
   2 -0.658498 -0.144519
   3 -0.015328  0.209711

In [127]:
df1.index.names

FrozenList([None, None])

In [128]:
df1.index.names=['Group','Number']

In [129]:
df1

A         B
Group Number                    
G1    1       1.069031  2.198842
      2       0.399686  0.476830
      3       0.249038 -0.306465
G2    1       0.906088  0.128585
      2      -0.658498 -0.144519
      3      -0.015328  0.209711

In [130]:
df1.loc['G1']

A         B
Number                    
1       1.069031  2.198842
2       0.399686  0.476830
3       0.249038 -0.306465

In [131]:
df1.loc['G1'].loc[2]

A    0.399686
B    0.476830
Name: 2, dtype: float64

In [133]:
df1.xs('G2')

A         B
Number                    
1       0.906088  0.128585
2      -0.658498 -0.144519
3      -0.015328  0.209711